### PR TITLE
release version 3.x

### LINKED ISSUE #11: add drive sensors: setpoint and drive mode
Would it be possible to add a temperature sensor for the set point and a boolean for whether or not drive is enabled?   Thanks!

### LINKED ISSUE #32: drive mode sensor has incorrect state_class measurement
```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:575
integration: Sensor (documentation, issues)
First occurred: 7:46:36 PM (1 occurrences)
Last logged: 7:46:36 PM

Entity sensor.gjkk6737j_drive_mode (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using state class 'measurement' which is impossible considering device class ('enum') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
```

### LINKED ISSUE #33: incorrect device_class for sensor drive_lidpaused
```

Error:

Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:270
integration: MQTT (documentation, issues)
First occurred: 7:46:35 PM (5 occurrences)
Last logged: 7:48:46 PM

Error 'expected SensorDeviceClass or one of 'date', 'enum', 'timestamp', 'apparent_power', 'aqi', 'atmospheric_pressure', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'data_rate', 'data_size', 'distance', 'duration', 'energy', 'energy_storage', 'frequency', 'gas', 'humidity', 'illuminance', 'irradiance', 'moisture', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'ph', 'pm1', 'pm10', 'pm25', 'power_factor', 'power', 'precipitation', 'precipitation_intensity', 'pressure', 'reactive_power', 'signal_strength', 'sound_pressure', 'speed', 'sulphur_dioxide', 'temperature', 'volatile_organic_compounds', 'volatile_organic_compounds_parts', 'voltage', 'volume', 'volume_storage', 'volume_flow_rate', 'water', 'weight', 'wind_speed' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/sensor/GJKK6737J/drive_lidpaused/config', message: '{'unique_id': 'GJKK6737J_drive_lidpaused', 'object_id': 'GJKK6737J_drive_lidpaused', 'name': 'Drive Lid Paused', 'availability': [{'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/bridge/availability'}, {'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/GJKK6737J/availability'}, {'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/GJKK6737J/drive/availability'}], 'device_class': 'opening', 'enabled_by_default': True, 'encoding': 'utf-8', 'qos': 0, 'state_topic': 'null/GJKK6737J/drive/lidpaused', 'device': {'configuration_url': 'https://fireboard.io/devices/180758/edit/', 'connections': [['mac', 'e8:31:cd:d3:41:4c']], 'identifiers': ['180758', 'GJKK6737J', '590b8e87-a282-441d-b357-5dceb2a62a14'], 'manufacturer': 'Fireboard Labs', 'model': 'FBX2D', 'name': 'Meat Master 3000', 'serial_number': 'GJKK6737J', 'sw_version': '3.5.13'}, 'platform': 'mqtt'}'

_Originally posted by @mattdevo1 in https://github.com/gordlea/fireboard2mqtt/pull/31#issuecomment-1998848701_
```

### LINKED ISSUE #38: nightmode is not available on all devices
The nightmode property does not show up on api request for devices that don’t have nightmode.

### PR DESCRIPTION
**Pull request by gordlea**
This is a complete rewrite in rust. It should fix many longstanding issues around the fireboard drive, as well as be much more memory and cpu efficient.

Tested with: 
* Fireboard2
* Fireboard Spark
* Fireboard Pro
* Yoder YS640S

Resolves #11 
Fixes #32 
Fixes #33
Fixes #38 

### How to beta test this release

1. Go to home-assistant addons, and then uninstall fireboard2mqtt.
2. Go to the addon store page, and remove "gordlea's Home Assistant add-on repository".
3. Add the repository back in with the following url: `https://github.com/gordlea/home-assistant-addons#beta`
4. Reinstall the fireboard2mqtt addon, it should be version 3.0.0-beta.x.
5. Configure the addon with your fireboard credentials

### CODE REVIEW

**Comment by gordlea** [comment]
@mattdevo1, @fdelacou, @buffalowolff, @alexownsall 3.0.0-beta.2 should be available in home-assistant addons now. 

Lets continue the testing discussion here.

**Comment by mattdevo1** [comment]
Two small issues that I found in the HA Core log. Sorry I don't know enough to understand what they mean, but passing them on if helpful...

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:575
integration: Sensor (documentation, issues)
First occurred: 7:46:36 PM (1 occurrences)
Last logged: 7:46:36 PM

Entity sensor.gjkk6737j_drive_mode (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using state class 'measurement' which is impossible considering device class ('enum') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:270
integration: MQTT (documentation, issues)
First occurred: 7:46:35 PM (5 occurrences)
Last logged: 7:48:46 PM

Error 'expected SensorDeviceClass or one of 'date', 'enum', 'timestamp', 'apparent_power', 'aqi', 'atmospheric_pressure', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'data_rate', 'data_size', 'distance', 'duration', 'energy', 'energy_storage', 'frequency', 'gas', 'humidity', 'illuminance', 'irradiance', 'moisture', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'ph', 'pm1', 'pm10', 'pm25', 'power_factor', 'power', 'precipitation', 'precipitation_intensity', 'pressure', 'reactive_power', 'signal_strength', 'sound_pressure', 'speed', 'sulphur_dioxide', 'temperature', 'volatile_organic_compounds', 'volatile_organic_compounds_parts', 'voltage', 'volume', 'volume_storage', 'volume_flow_rate', 'water', 'weight', 'wind_speed' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/sensor/GJKK6737J/drive_lidpaused/config', message: '{'unique_id': 'GJKK6737J_drive_lidpaused', 'object_id': 'GJKK6737J_drive_lidpaused', 'name': 'Drive Lid Paused', 'availability': [{'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/bridge/availability'}, {'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/GJKK6737J/availability'}, {'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/GJKK6737J/drive/availability'}], 'device_class': 'opening', 'enabled_by_default': True, 'encoding': 'utf-8', 'qos': 0, 'state_topic': 'null/GJKK6737J/drive/lidpaused', 'device': {'configuration_url': 'https://fireboard.io/devices/180758/edit/', 'connections': [['mac', 'e8:31:cd:d3:41:4c']], 'identifiers': ['180758', 'GJKK6737J', '590b8e87-a282-441d-b357-5dceb2a62a14'], 'manufacturer': 'Fireboard Labs', 'model': 'FBX2D', 'name': 'Meat Master 3000', 'serial_number': 'GJKK6737J', 'sw_version': '3.5.13'}, 'platform': 'mqtt'}'

**Comment by gordlea** [comment]
Good catch! I'll fix it up as soon as I get a chance.

**Comment by gordlea** [comment]
Beta 4 should be available on home-assistant addons repo now, give it a try @mattdevo1

**Comment by gordlea** [comment]
BTW I am away for the next couple of days, so next update will be Thursday or so.

**Comment by mattdevo1** [comment]
> Beta 4 should be available on home-assistant addons repo now, give it a try @mattdevo1

Hrmm...I'm not seeing Beta 4, only Beta 3. Any ideas?

**Comment by alexownsall** [comment]
I'm still getting this error with beta.3

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[12:48:37] INFO: mqtt://core-mosquitto:1883
[12:48:37] INFO: Starting fireboard2mqtt
[12:48:37] INFO: drive enabled: false
 DEBUG fireboard2mqtt > config loaded successfully
 DEBUG fireboard2mqtt::fireboard_watcher > client authenticated successfully
 INFO  fireboard2mqtt::fireboard_watcher > checking fireboard api for updates
 ERROR fireboard2mqtt::fireboard_api     > Error parsings devices: error decoding response body: invalid type: map, expected unit at line 1 column 1253
 ERROR fireboard2mqtt::fireboard_watcher > Error fetching devices: error decoding response body: invalid type: map, expected unit at line 1 column 1253

Caused by:
    invalid type: map, expected unit at line 1 column 1253
 INFO  fireboard2mqtt                    > Current physical memory usage: 31 MB
 DEBUG fireboard2mqtt                    > there are 0 devices online
 DEBUG fireboard2mqtt                    > updating from fireboard cloud api in 60 seconds

**Comment by thanatars** [comment]
I'm seeing this error and with Beta3. It just keeps repeating.

 ERROR fireboard2mqtt::fireboard_api     > Error parsings devices: error decoding response body: missing field `nightmode` at line 1 column 1207
 ERROR fireboard2mqtt::fireboard_watcher > Error fetching devices: error decoding response body: missing field `nightmode` at line 1 column 1207

Caused by:
    missing field `nightmode` at line 1 column 1207
 INFO  fireboard2mqtt                    > Current physical memory usage: 31.2 MB
 DEBUG fireboard2mqtt                    > there are 0 devices online
 DEBUG fireboard2mqtt                    > updating from fireboard cloud api in 60 seconds
 INFO  fireboard2mqtt::fireboard_watcher > checking fireboard api for updates
 ERROR fireboard2mqtt::fireboard_api     > Error parsings devices: error decoding response body: missing field `nightmode` at line 1 column 1207
 ERROR fireboard2mqtt::fireboard_watcher > Error fetching devices: error decoding response body: missing field `nightmode` at line 1 column 1207

**Comment by gordlea** [comment]
@alexownsall What kind of fireboard do you have? What is the model?

**Comment by alexownsall** [comment]
> @alexownsall What kind of fireboard do you have? What is the model?

Fireboard 2

**Comment by alexownsall** [comment]
With the latest beta, I am getting a different error now.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[18:43:08] INFO: mqtt://core-mosquitto:1883
[18:43:08] INFO: Starting fireboard2mqtt
[18:43:08] INFO: drive enabled: false
 DEBUG fireboard2mqtt > config loaded successfully
 DEBUG fireboard2mqtt::fireboard_watcher > client authenticated successfully
 INFO  fireboard2mqtt::fireboard_watcher > checking fireboard api for updates
 ERROR fireboard2mqtt::fireboard_api     > Error parsings devices: error decoding response body: invalid type: null, expected usize at line 1 column 1110
 ERROR fireboard2mqtt::fireboard_watcher > Error fetching devices: error decoding response body: invalid type: null, expected usize at line 1 column 1110

Caused by:
    invalid type: null, expected usize at line 1 column 1110
 INFO  fireboard2mqtt                    > Current physical memory usage: 32.8 MB
 DEBUG fireboard2mqtt                    > there are 0 devices online
 DEBUG fireboard2mqtt                    > updating from fireboard cloud api in 60 seconds

**Comment by alexownsall** [comment]
I also factory reset and removed my device from my account before adding it again. Still no change.

**Comment by mattdevo1** [comment]
> Beta 4 should be available on home-assistant addons repo now, give it a try @mattdevo1

I installed Beta 6 tonight, but I still get the same error in the HA Core Log (see below). Everything seems to work correctly though, sorry I can't be more help with the error, I don't know enough to interpret what it means.

Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:270
integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 7:45:33 PM (1 occurrences)
Last logged: 7:45:33 PM

Error 'expected SensorDeviceClass or one of 'date', 'enum', 'timestamp', 'apparent_power', 'aqi', 'atmospheric_pressure', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'data_rate', 'data_size', 'distance', 'duration', 'energy', 'energy_storage', 'frequency', 'gas', 'humidity', 'illuminance', 'irradiance', 'moisture', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'ph', 'pm1', 'pm10', 'pm25', 'power_factor', 'power', 'precipitation', 'precipitation_intensity', 'pressure', 'reactive_power', 'signal_strength', 'sound_pressure', 'speed', 'sulphur_dioxide', 'temperature', 'volatile_organic_compounds', 'volatile_organic_compounds_parts', 'voltage', 'volume', 'volume_storage', 'volume_flow_rate', 'water', 'weight', 'wind_speed' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/sensor/GJKK6737J/drive_lidpaused/config', message: '{'unique_id': 'GJKK6737J_drive_lidpaused', 'object_id': 'GJKK6737J_drive_lidpaused', 'name': 'Drive Lid Paused', 'availability': [{'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/bridge/availability'}, {'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/GJKK6737J/availability'}, {'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/GJKK6737J/drive/availability'}], 'device_class': 'opening', 'enabled_by_default': True, 'encoding': 'utf-8', 'qos': 0, 'state_topic': 'null/GJKK6737J/drive/lidpaused', 'device': {'configuration_url': 'https://fireboard.io/devices/180758/edit/', 'connections': [['mac', 'e8:31:cd:d3:41:4c']], 'identifiers': ['180758', 'GJKK6737J', '590b8e87-a282-441d-b357-5dceb2a62a14'], 'manufacturer': 'Fireboard Labs', 'model': 'FBX2D', 'name': 'Meat Master 3000', 'serial_number': 'GJKK6737J', 'sw_version': '3.5.13'}, 'platform': 'mqtt'}'

**Comment by gordlea** [comment]
Hmm, not sure if this is the cause of the error, but i do notice some topics like `null/GJKK6737J/availability` in the log output you posted. It should be more like: `fireboard2mqtt/GJKK6737J/availability`. 

Can you try setting fireboard2mqtt topic prefix to `fireboard2mqtt` in the addon config? This should be defaulting to `fireboard2mqtt` but it seems like it isn't in your case.

**Comment by mattdevo1** [comment]
> Hmm, not sure if this is the cause of the error, but i do notice some topics like `null/GJKK6737J/availability` in the log output you posted. It should be more like: `fireboard2mqtt/GJKK6737J/availability`. 
> 
> Can you try setting fireboard2mqtt topic prefix to `fireboard2mqtt` in the addon config? This should be defaulting to `fireboard2mqtt` but it seems like it isn't in your case.
> 
> 

Is that the mqtt_topic_prefix setting in the add on config? If so, I set it to fireboard2mqtt and restarted HA, but the same error is still occurring in the HA Core Log.

**Comment by gordlea** [comment]
Actually, I can't quite get the images to push correctly, it will have to wait. I'll let you know here when i have a new update.

**Comment by gordlea** [comment]
Just released beta.8, it adds extra debug logging when reading devices fails. 

If you see an error here, please post the JSON output of the devices, there appears to be some differences in the format of the response based on what type of fireboard device is attached to the account.

**Comment by thanatars** [comment]
Still getting errors with .8.
For reference I have a Fireboard Spark and a Yoder YS640S.


ERROR fireboard2mqtt::fireboard_api     > Error parsing devices: invalid type: map, expected unit at line 1 column 3223 from response body: [{"uuid":"76941e0d-06a3-44e5-9157-6f3185de8a80","id":233792,"title":"Instant Read","hardware_id":"G9K48CDM2","created":"2024-01-11T19:42:42.306Z","latest_temps":[],"device_log":{"versionEspHal":"HAL: V1R2;MSP: 1.0.3;","onboardTemp":75.5576515368969,"versionImage":"201703260554","vBattPer":0.8729960621856658,"macNIC":"e8:9f:6d:25:78:e0","bleClientMAC":"","date":"2024-03-16 23:45:47 UTC","version":"1.4.10","signallevel":-70,"internalIP":"192.168.1.224","auxPort":"","deviceID":"76941e0d-06a3-44e5-9157-6f3185de8a80","commercialMode":"false","vBatt":3.908270555412167,"showdecimal":false,"memUsage":"1.0M/2.2M","tempFilter":"true","ssid":"XXXXXX","macAP":"b6:95:75:64:56:ce","syncmode":false,"boardID":"G9K48CDM2","uptime":"0:00","publicIP":"XXX.XXX.XXX.XXX","nfc_tag_db":{"last_updated_min":9.223372036854776e+18,"last_updated_max":0},"txpower":78,"mode":"Managed","versionJava":"7.6.5","drivesettings":"{\"p\":0,\"s\":0,\"d\":0,\"ms\":0,\"f\":0,\"l\":0}","frequency":"2.4 GHz","contrast":"7","linkquality":"60/100","model":"FBXIR","cpuUsage":"62%","diskUsage":"0.2M/4.0M","bleSignalLevel":0,"versionNode":"5.0.0","vBattPerRaw":0.8729960621856658,"band":"802.11bgn","versionUtils":"6.1.3"},"last_templog":"2024-03-16T23:45:42Z","last_battery_reading":0.8729960621856658,"channels":[{"created":"2024-03-17T19:43:04Z","enabled":true,"channel":1,"sessionid":6749619,"channel_label":"Channel 1","id":33344022,"alerts":[]},{"created":"2024-03-17T19:43:04Z","enabled":true,"channel":2,"sessionid":6749619,"channel_label":"Channel 2","id":33344023,"alerts":[]}],"fbj_version":"7.6.5","fbn_version":"5.0.0","fbu_version":"6.1.3","version":"1.4.10","probe_config":"8|0|0.0|8|0|0.0","last_drivelog":null,"channel_count":2,"degreetype":2,"model":"FBXIR","active":true,"auto_session":true},{"uuid":"524d312b-6077-4620-8bc4-68419c5a1d54","id":236147,"title":"Yoder","hardware_id":"GM4JR9KCJ","created":"2024-02-06T19:39:16.699Z","latest_temps":[],"device_log":{"versionEspHal":"HAL: V1R2;","onboardTemp":87.35,"versionImage":"201703260554","vBattPer":0,"macNIC":"c4:de:e2:cf:6d:7c","bleClientMAC":"40:e8:37:79:58:d6","date":"2024-03-17 21:16:28 UTC","timeZoneBT":"America/New_York","signallevel":-54,"yfbVersion":"1.0.53","internalIP":"192.168.1.219","auxPort":"","yfbPower":false,"commercialMode":"false","vBatt":0,"memUsage":"1.1M/4.2M","tempFilter":"true","ssid":"XXXXX","macAP":"b6:95:75:64:56:ce","deviceID":"524d312b-6077-4620-8bc4-68419c5a1d54","boardID":"GM4JR9KCJ","uptime":"25:09","publicIP":"XXX.XXX.XXX.XXX","vBattPerRaw":0,"txpower":78,"mode":"Managed","versionJava":"7.6.5","drivesettings":"{\"p\":0,\"s\":0,\"d\":0,\"ms\":100,\"f\":0,\"l\":1}","frequency":"2.4 GHz","contrast":"7","linkquality":"94/100","model":"YFBXC","cpuUsage":"375%","yfbModel":"YS640","diskUsage":"0.6M/4.0M","version":"1.0.53","bleSignalLevel":-88,"versionNode":"5.0.0","band":"802.11bgn","versionUtils":"6.1.3"},"last_templog":"2024-03-17T20:05:17Z","last_battery_reading":0,"channels":[{"created":"2024-03-17T00:26:08Z","enabled":true,"channel":1,"sessionid":6749619,"channel_label":"Pit","id":33321419,"alerts":[]},{"created":"2024-03-17T00:26:08Z","enabled":true,"channel":2,"sessionid":6749619,"channel_label":"Probe 1","id":33321420,"alerts":[{"temp_max":205.0,"created":"2024-03-17T00:26:08Z","temp_min":null,"channel":2,"time_start":null,"time_stop":null,"notify_app":true,"minutes_repeat":30,"session_id":6749619,"device_id":236147,"enabled":true,"notify_sms":false,"minutes_buffer":0,"notify_email":false,"id":7392812}]},{"created":"2024-03-17T00:26:08Z","enabled":true,"channel":3,"sessionid":6749619,"channel_label":"Probe 2","id":33321421,"alerts":[]}],"fbj_version":"7.6.5","fbn_version":"5.0.0","fbu_version":"6.1.3","version":"1.0.53","probe_config":"8|0|0.0|8|0|0.0|8|0|0.0","last_drivelog":{"profiletype":0,"pg_step_position":0,"degreetype":2,"modetype":0,"pg_elapsed":0,"vbatt":0.0,"tiedchannel":1,"pg_step_uuid":null,"setpoint":0.0,"device_id":236147,"powermode":3,"var3":0.0,"jsonraw":"{\"c\":\"2024-03-17 20:05:11 UTC\",\"d\":0.20013299999999976,\"pt\":0,\"mt\":0,\"vb\":0,\"dr\":3,\"tc\":1,\"dt\":2,\"p\":0,\"ct\":0,\"u\":false,\"programinfo\":{\"elapsed\":0,\"stepuuid\":null,\"lastupdated\":\"2024-03-16 20:07:11 UTC\",\"state\":0,\"uuid\":null,\"stepposition\":0},\"v1\":0,\"v2\":0,\"sp\":0,\"v3\":0,\"pm\":3}","created":"2024-03-17T20:05:11Z","pg_uuid":null,"drivetype":3,"var2":0.0,"pg_state":0,"pg_step_index":null,"userinitiated":false,"driveper":0.2,"id":1709601663,"var1":0.0,"currenttemp":0.0},"channel_count":3,"degreetype":2,"model":"YFBXC","active":true,"auto_session":true}]
 ERROR fireboard2mqtt::fireboard_watcher > Error fetching devices: invalid type: map, expected unit at line 1 column 3223
 INFO  fireboard2mqtt                    > Current physical memory usage: 29.5 MB
 DEBUG fireboard2mqtt                    > there are 0 devices online
 DEBUG fireboard2mqtt                    > updating from fireboard cloud api in 60 seconds

**Comment by gordlea** [comment]
Thank you @thanatars, that was exactly what I needed. Can you try beta.9 and see if that fixes the issue?

**Comment by thanatars** [comment]
> Thank you @thanatars, that was exactly what I needed. Can you try beta.9 and see if that fixes the issue?

That looks to have fixed my issues!! It works for the Spark. I plan to pull the smoker out on Friday. I'll report back and let you know how it turns out. Thanks for working out the bugs.

**Comment by alexownsall** [comment]
So the good news is that this fixed my connection issues. I can now see my device and get updates. I assume the slowish polling rate is to account for limits in their API, so that's understandable. 

I do think there is room for improvement with displaying battery data even if no probes are inserted, which now it says unavailable and that the device is offline. It only shows battery and online if a probe is inserted. Is that the API response directly or something you coded?

**Comment by gordlea** [comment]
@alexownsall The issue is that using the [api](https://docs.fireboard.io/app/api.html#Device-API) there is not a great way to tell if the device is actually on or not. I'm doing it by checking if `latest_temps` has any readings available (in the api, any readings older than 60 seconds are not included). 

I still update the battery reading when polling to see if there are any temp values, but it would be stale data if the device is actually offline.

I will see if I can use device_log.date to tell if the device is online even if no probes are connected, i think it updates every 5 minutes or so.

**Comment by gordlea** [comment]
@alexownsall I think that should work better now, if there are no probes online it uses device_log.date to determine if it's online.

**Comment by alexownsall** [comment]
@gordlea great work. Works as expected.

**Comment by mattdevo1** [comment]
> @alexownsall I think that should work better now, if there are no probes online it uses device_log.date to determine if it's online.
> 
> beta.10 is available now

I'm still getting the below error on my HA Core Log with Beta 10.

Everything seems to be operating correctly. And I really like the change you made to determine if the device is online without probes being attached, nice!

Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:270
integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 6:43:54 AM (1 occurrences)
Last logged: 6:43:54 AM

Error 'expected SensorDeviceClass or one of 'date', 'enum', 'timestamp', 'apparent_power', 'aqi', 'atmospheric_pressure', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'data_rate', 'data_size', 'distance', 'duration', 'energy', 'energy_storage', 'frequency', 'gas', 'humidity', 'illuminance', 'irradiance', 'moisture', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'ph', 'pm1', 'pm10', 'pm25', 'power_factor', 'power', 'precipitation', 'precipitation_intensity', 'pressure', 'reactive_power', 'signal_strength', 'sound_pressure', 'speed', 'sulphur_dioxide', 'temperature', 'volatile_organic_compounds', 'volatile_organic_compounds_parts', 'voltage', 'volume', 'volume_storage', 'volume_flow_rate', 'water', 'weight', 'wind_speed' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/sensor/GJKK6737J/drive_lidpaused/config', message: '{'unique_id': 'GJKK6737J_drive_lidpaused', 'object_id': 'GJKK6737J_drive_lidpaused', 'name': 'Drive Lid Paused', 'availability': [{'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/bridge/availability'}, {'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/GJKK6737J/availability'}, {'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'null/GJKK6737J/drive/availability'}], 'device_class': 'opening', 'enabled_by_default': True, 'encoding': 'utf-8', 'qos': 0, 'state_topic': 'null/GJKK6737J/drive/lidpaused', 'device': {'configuration_url': 'https://fireboard.io/devices/180758/edit/', 'connections': [['mac', 'e8:31:cd:d3:41:4c']], 'identifiers': ['180758', 'GJKK6737J', '590b8e87-a282-441d-b357-5dceb2a62a14'], 'manufacturer': 'Fireboard Labs', 'model': 'FBX2D', 'name': 'Meat Master 3000', 'serial_number': 'GJKK6737J', 'sw_version': '3.5.13'}, 'platform': 'mqtt'}'

**Comment by gordlea** [comment]
@mattdevo1 I think I know what's going on, there is a retained mqtt message from an earlier version where the lidpaused sensor discovery message was saved at: 

`homeassistant/sensor/GJKK6737J/drive_lidpaused/config`

It should have been a binary sensor, and so the proper path was:

`homeassistant/binary_sensor/GJKK6737J/drive_lidpaused/config`

Can you install an mqtt client like [mqtt explorer](https://mqtt-explorer.com/), and delete the first path above using it? I don't think the error messages are actually causing any problems, but i'm sure it's annoying to have the error message showing up.

**Comment by gordlea** [comment]
So I think we're getting close to a release. 

@buffalowolff Can you confirm it's working with the fireboard pro?

@thanatars Can you confirm if it's working with the Yoder?

**Comment by buffalowolff** [comment]
All channels seem to work on the pro now, including drive.  I haven't
tested lid open.  One odd thing is that channel labels show up as separate
channels but not a big deal (breast, thigh, pit temp)
[image: image.png]

**Comment by mattdevo1** [comment]
> @mattdevo1 I think I know what's going on, there is a retained mqtt message from an earlier version where the lidpaused sensor discovery message was saved at:
> 
> `homeassistant/sensor/GJKK6737J/drive_lidpaused/config`
> 
> It should have been a binary sensor, and so the proper path was:
> 
> `homeassistant/binary_sensor/GJKK6737J/drive_lidpaused/config`
> 
> Can you install an mqtt client like [mqtt explorer](https://mqtt-explorer.com/), and delete the first path above using it? I don't think the error messages are actually causing any problems, but i'm sure it's annoying to have the error message showing up.

Thank you! Deleted the path above and restarted HA, the error hasn't reappeared in the log. 

I did just notice that the Drive sensors appear to be unavailable now though. They were working in an earlier beta version, I'm not sure exactly when they stopped working for me.

Here is what I'm seeing in the add on log if helpful:

DEBUG fireboard2mqtt                    > drive support not enabled

**Comment by thanatars** [comment]
> So I think we're getting close to a release.
> 
> @buffalowolff Can you confirm it's working with the fireboard pro?
> 
> @thanatars Can you confirm if it's working with the Yoder?

I'm running the Yoder right now and it is reporting all of the sensors properly. I'll report back if I see any errors.

**Comment by gordlea** [comment]
> All channels seem to work on the pro now, including drive. I haven't tested lid open. One odd thing is that channel labels show up as separate channels but not a big deal (breast, thigh, pit temp) [image: image.png]

@buffalowolff Can you explain more what you mean? I'm not sure the image attachment worked. Oh, if you rename a channel in the fireboard app, does it duplicate in home assistant or something?

**Comment by buffalowolff** [comment]
if I apply a label to a channel using the FireBoard app, it shows up as a
separate entity that gets no temperature value in home assistant.  I will
test some more scenarios in a little while

**Comment by gordlea** [comment]
Okay @buffalowolff, it should handle label changes properly now. Try beta.11.

**Comment by buffalowolff** [comment]
Will do. I don't see an available update

**Comment by gordlea** [comment]
> Will do. I don't see an available update

If you go to the add-ons page, then click the little circle arrow button on the top right it should check for updates.

**Comment by buffalowolff** [comment]
Weird, I even removed and reinstalled it.  Updated now and it looks great.
Nice job.  As of now everything looks good to me.  I'll test more with the
spark whenever they send it back to me.

**Comment by mattdevo1** [comment]
@gordlea im sure you would have done this, but just a reminder that you might want to turn the default debug logging off when you push the final 3.0 release?

**Comment by gordlea** [comment]
@mattdevo1 I might leave it on until 3.0.1 just in case any more bugs turn up. :)

Thanks everyone for the help testing, just building the updated docker images now. You'll have to change back to the non-beta repo to install.

**Comment by gordlea** [comment]
If you guys have any ideas for future ideas / use cases, we can discuss here: https://github.com/gordlea/fireboard2mqtt/discussions/39

**Comment by mattdevo1** [comment]
> @mattdevo1 I might leave it on until 3.0.1 just in case any more bugs turn up. :)
> 
> Thanks everyone for the help testing, just building the updated docker images now. You'll have to change back to the non-beta repo to install.

Makes sense!

I just installed 3.0 and everything seems to be working perfectly. Great job, thank you!

**Pull request merged**
